#custom property
file:
  path: C:/fileupload/webProjectBase
spring:
  datasource:
    primary:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@office.solutis.co.kr:54000:UTF8CUR
      username: s_esight
      password: thffnxltm!138
    secondary:
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      #url: jdbc:oracle:thin:@office.solutis.co.kr:54000:UTF8CUR
      #username: s_esight_gp
      #password: lca5534!138
logging:
  file:
    path: C:/logs/webProjectBase
    name: webLog
  logback:
    rollingpolicy:
      max-history: 30
  level:
    sql: ERROR